import structlog
from wire.schema.canonical import CanonicalDesignSchema, ComponentNode
from wire.compilers.sanitizer import HtmlSanitizer

logger = structlog.get_logger(__name__)


class VueAdapter:
    """
    CIDS → Vue SFC (Single File Component) compiler.
    Independent adapter consuming the Canonical Intermediate Design Schema.

    NOTE ON SHADOW DOM COMPILATION:
    Shadow DOM content (node.shadow_root) is compiled into browser-native
    Declarative Shadow DOM templates (<template shadowrootmode="open">).
    Because Vue's virtual DOM reactivity and SFC compiler do not natively
    diff or update elements inside declarative shadow roots after mount,
    all compiled shadow root subtrees are STATIC-ONLY. They will render
    correctly on initial mount, but dynamic framework state/props updates
    inside these subtrees are not supported.
    """

    def compile(self, cids: CanonicalDesignSchema) -> str:
        logger.info("compiling_cids_to_vue", url=cids.url)

        template = self._render_template(cids.root)
        script = self._render_script(cids)
        style = self._render_style(cids)

        return f"<template>\n{template}\n</template>\n\n{script}\n\n{style}\n"

    def _render_template(self, node: ComponentNode, indent: int = 2) -> str:
        prefix = " " * indent
        tag = node.tag

        if tag == "#text":
            return prefix + (node.text_content or "")

        # Unsafe tags filtering (defense-in-depth)
        if tag in HtmlSanitizer.UNSAFE_TAGS and tag != "#shadow-root":
            return ""

        if tag == "#shadow-root":
            children_str = "\n".join([self._render_template(c, indent + 2) for c in node.children])
            return f'{prefix}<template shadowrootmode="open">\n{children_str}\n{prefix}</template>'

        attrs_parts = []
        for key, value in node.attributes.items():
            if key == "style":
                continue
            if key.lower().startswith("on"):
                continue
            if key.lower() in {"href", "src", "action", "formaction"}:
                if not HtmlSanitizer._is_safe_uri(value):
                    continue
            attrs_parts.append(f'{key}="{value}"')

        if node.styles:
            style_parts = []
            for k, v in node.styles.items():
                sanitized_val = HtmlSanitizer._sanitize_style_string(v)
                if sanitized_val:
                    style_parts.append(f"{k}: {sanitized_val}")
            if style_parts:
                style_str = "; ".join(style_parts)
                attrs_parts.append(f'style="{style_str}"')

        attrs = (" " + " ".join(attrs_parts)) if attrs_parts else ""

        # Self-closing tags (only if no children, no text, and no shadow_root)
        if not node.children and not node.text_content and not node.shadow_root:
            return f"{prefix}<{tag}{attrs} />"

        content = node.text_content or ""
        children_parts = []
        if node.shadow_root:
            children_parts.append(self._render_template(node.shadow_root, indent + 2))
        for c in node.children:
            children_parts.append(self._render_template(c, indent + 2))

        inner = content + ("\n" + "\n".join(children_parts) if children_parts else "")

        return f"{prefix}<{tag}{attrs}>\n{prefix}  {inner}\n{prefix}</{tag}>"

    def _render_script(self, cids: CanonicalDesignSchema) -> str:
        return (
            "<script setup>\n"
            "// Auto-generated by WIRE Vue Adapter\n"
            f"// Source: {cids.url}\n"
            "</script>"
        )

    def _render_style(self, cids: CanonicalDesignSchema) -> str:
        lines = ["<style scoped>"]
        if cids.tokens.colors:
            lines.append(":root {")
            for name, value in cids.tokens.colors.items():
                lines.append(f"  --color-{name}: {value};")
            lines.append("}")
        if cids.tokens.typography:
            lines.append("body {")
            if "base" in cids.tokens.typography:
                lines.append(f"  font-family: {cids.tokens.typography['base']};")
            lines.append("}")
        lines.append("</style>")
        return "\n".join(lines)
