"""add reconstruction_jobs table

Revision ID: cfc8461062df
Revises: cd229e892403
Create Date: 2026-07-04 19:17:28.210186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cfc8461062df"
down_revision: Union[str, Sequence[str], None] = "cd229e892403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconstruction_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reconstruction_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reconstruction_jobs_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reconstruction_jobs_project_id"),
            ["project_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_reconstruction_jobs_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reconstruction_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reconstruction_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_reconstruction_jobs_project_id"))
        batch_op.drop_index(batch_op.f("ix_reconstruction_jobs_id"))

    op.drop_table("reconstruction_jobs")
    # ### end Alembic commands ###
